project:
  title: "リズムペディア.com"
  type: website
  output-dir: .site
  preview:
    port: 5150
    browser: false
  resources:
    - Ads.txt
  pre-render: bin/render-sidebar.sh

website:
  title: "律動図鑑(リズムペディア)"
  description: "グルーヴを科学する律動図鑑〜リズムペディア"
  site-url: "https://rhythmpedia.com/"
  page-navigation: true     # show Previous / Next buttons in the footer
  bread-crumbs: true
#  site-url: "https://ats4u.github.io/jpn-master-workinglog-markdown/"
#  announcement:
#    content: |
#       <div class="top-banner">
#       <img src="attachments/rhythmpedia-header3.png" style="width:100vw"/>
#      </div>
#    type: primary
#    position: above-navbar
#    dismissable: false
  navbar:
    right:
      - href: index.qmd
        text: "トップに戻る"
#    logo: /attachments/rhythmpedia-logo-dark.png
#    logo: attachments/rhythmpedia-header2.png
  sidebar:
    style: "docked"
    search: true
    logo: /attachments/rhythmpedia-logo-dark.png
    collapse-level: 1
    contents: []
format:
  html:
    theme:
      light : [ cosmo,  .assets/websites/theme.scss, .assets/websites/theme-light.scss ]
      dark  : [ darkly, .assets/websites/theme.scss, .assets/websites/theme-dark.scss  ]
    lightbox: true
    filters:
      - filters/include-files.lua
#      - filters/obsidian-image-dimensions.lua
    css: assets/styles.css
    toc: true
    toc-location: right
    toc-depth: 7
    toc-expand: 1
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6838486775293179" crossorigin="anonymous"></script>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <script type="module" src="/assets/toc-ul.mjs"></script>
    grid:
      sidebar-width: 500px
      body-width: 800px
      margin-width: 600px
      gutter-width: 1.5rem

metadata-files:
  - _sidebar.yml
