project:
  title: "リズムペディア.com"
  type: website
  output-dir: .site
#  execute-dir: project
  preview:
    port: 5150
#    browser: false
#    watch-inputs: false
    browser: false
  render:
    - "**/*.qmd"        # render only qmd
    - "!**/master*.md"  # explicitly ignore master*.md anywhere 
    - "!**/master*.qmd" # explicitly ignore master*.md anywhere 
    - "!drafts/*"       # exclude paths
  post-render:
    - bin/rhythmpedia-sitemap.py   # Sun, 31 Aug 2025 03:22:23 +0900 runs after every build

resources:
  - Ads.txt
  - _redirects
  - 404.html

website:
  title: "律動図鑑(リズムペディア)"
  description: "グルーヴを科学する律動図鑑〜リズムペディア"
  site-url: "https://rhythmpedia.com/"
  site-path: /
  page-footer:
    left: "© 2018-2025 律動図鑑リズムペディア — All rights reserved."
    right: |
      \|
      [リズムペディアについて](/about/rhythmpedia/ja/) |
      [運営者](/about/publisher/ja/) |
      [連絡先](/contact/ja/) |
      [問い合わせ](/contact-form/ja/) |
      [免責事項](/disclaimer/ja/) |
      <br/>
      \|
      [プライバシーポリシー](/privacy-policy/ja/) |
      <a href="/cookies/en/">Cookie Policy</a> |
      <a href="#" id="cookie-settings" rel="nofollow">Cookie Settings</a> |

  page-navigation: true     # show Previous / Next buttons in the footer
  bread-crumbs: true
#  site-url: "https://ats4u.github.io/jpn-master-workinglog-markdown/"
#  announcement:
#    content: |
#       <div class="top-banner">
#       <img src="attachments/rhythmpedia-header3.png" style="width:100vw"/>
#      </div>
#    type: primary
#    position: above-navbar
#    dismissable: false
  navbar:
    right:
      - href: index.qmd
        text: "トップに戻る"
  sidebar:
    style: "docked"
    logo: /attachments/rhythmpedia-logo-dark.png
    collapse-level: 1
    contents: []
# execute:
#  freeze: auto            # optional: avoids re-execution unless sources change
metadata:
  lilypond-preamble: "filters/lilypond-preamble.ly"
format:
  html:
    theme:
      light : [ cosmo,  .assets/websites/theme.scss, .assets/websites/theme-light.scss ]
      dark  : [ darkly, .assets/websites/theme.scss, .assets/websites/theme-dark.scss  ]
    lightbox: true
    reference-location: block
    filters:
      - filters/meta-dates.lua
      - filters/include-files.lua
      - lilypond.lua
#      - filters/obsidian-image-dimensions.lua
    css: assets/styles.css
    toc: true
    toc-location: right
    toc-depth: 7
    toc-expand: 1
    include-in-header:
      - text: |
          <script async type="module" src="/assets/ats4u-twitter-video.mjs"></script>
          <link href="/assets/groovespace.css" rel="stylesheet" />
          <script async type="module" src="/assets/groovespace.mjs"></script>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6838486775293179" crossorigin="anonymous"></script>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <script async type="module" src="/assets/toc-ul.mjs"></script>
          <script async type="module" src="/assets/cookie-settings.mjs"></script>
          <script 
            async
            id="Cookiebot" 
            src="https://consent.cookiebot.com/uc.js" 
            data-cbid="edc31cf5-a736-498e-916b-965351c95f41" 
            data-blockingmode="auto" 
            type="text/javascript">
          </script>
          <script data-cookieconsent="marketing">
            (adsbygoogle = window.adsbygoogle || []).push({
              google_ad_client: "ca-pub-6838486775293179",
              enable_page_level_ads: true
            });
          </script>

    grid:
      sidebar-width: 300px
      body-width: 1000px
      margin-width: 600px
      gutter-width: 1.5rem

metadata-files:
  - _sidebar-ja.generated.yml
