project:
  title: "リズムペディア.com"
  type: website
  output-dir: .site
  preview:
    port: 4141
    browser: false
  resources:
    - ads.txt
filters: [ include-files.lua ]
website:
  title: "リズムペディア.com"
  description: "グルーヴを科学するリズムペディア.com"
  site-url: "https://rhythmpedia.com/"
#  site-url: "https://ats4u.github.io/jpn-master-workinglog-markdown/"
#  announcement:
#    content: |
#       <div class="top-banner">
#       <img src="attachments/rhythmpedia-header3.png" style="width:100vw"/>
#      </div>
#    type: primary
#    position: above-navbar
#    dismissable: false
  navbar:
    right:
      - href: index.md
        text: "ホーム"
      - about.qmd
    logo: attachments/rhythmpedia-header2.png
  sidebar:
    style: "docked"
    search: true
    contents:
      - text:  "ホーム"
        href: index.md
      - text: "グルーヴを科学する"
        href: what-is-science.md
      - text: "縦乗りとは何か"
        href: tatenori.md
    logo: /attachments/rhythmpedia-header5v2.png
format:
  html:
    theme:
      light : [ cosmo, theme.scss, theme-light.scss ]
      dark  : [ darkly, theme.scss, theme-dark.scss ]
    css: styles.css
#    include-in-header:
#      - file: banner.html
    toc: true
    toc-location: right
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6838486775293179" crossorigin="anonymous"></script>

