project:
  title: "リズムペディア.com"
  type: website
  output-dir: .site
  preview:
    port: 5150
    browser: false
  resources:
    - Ads.txt

website:
  title: "律動図鑑(リズムペディア)"
  description: "グルーヴを科学する律動図鑑〜リズムペディア"
  site-url: "https://rhythmpedia.com/"
#  site-url: "https://ats4u.github.io/jpn-master-workinglog-markdown/"
#  announcement:
#    content: |
#       <div class="top-banner">
#       <img src="attachments/rhythmpedia-header3.png" style="width:100vw"/>
#      </div>
#    type: primary
#    position: above-navbar
#    dismissable: false
  navbar:
    right:
      - href: index.qmd
        text: "トップに戻る"
#    logo: /attachments/rhythmpedia-logo-dark.png
#    logo: attachments/rhythmpedia-header2.png
  sidebar:
    style: "docked"
    search: true
    logo: /attachments/rhythmpedia-logo-dark.png
    contents:
      - section: "律動図鑑(リズムペディア)"
        href: index.qmd
        contents:
          - text: トップ
            href: index.qmd
      - section: "オフビートカウント理論"
        contents:
          - ./tatenori-theory/index.md
          - ./beat-orientation/index.md
#          - ./metadivision/index.md
#          - ./three-n-rhythm/index.md
          - ./distributed-groove-theory/index.md
          - ./offbeat-count-theory/index.md
#          - ./practical-offbeat-count/index.md
#          - ./polyrhythm/index.md
          - ./tatenori-and-psychology/index.md
#          - ./mechanism-behind-tatenori/index.md
#          - ./influence-of-japanese-language-on-cognition/index.md
format:
  html:
    theme:
      light : [ cosmo,  .assets/websites/theme.scss, .assets/websites/theme-light.scss ]
      dark  : [ darkly, .assets/websites/theme.scss, .assets/websites/theme-dark.scss  ]
    lightbox: true
    filters:
      - filters/include-files.lua
#      - filters/obsidian-image-dimensions.lua
    css: styles.css
#    include-in-header:
#      - file: banner.html
    toc: true
    toc-location: right
    toc-depth: 7
    toc-expand: 1
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6838486775293179" crossorigin="anonymous"></script>
          <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <script type="module" src="assets/toc-ul.mjs"></script>
    grid:
      sidebar-width: 300px
      body-width: 800px
      margin-width: 600px
      gutter-width: 1.5rem

