
website:
  sidebar:
    style: "docked"
    search: true
    logo: /attachments/rhythmpedia-logo-dark.png
    contents:
      - section: "律動図鑑(リズムペディア)"
        href: index.qmd
        contents:
          - text: トップ
            href: index.qmd
      - section: "オフビートカウント理論"
        contents:
          - ./tatenori-theory/ja/
          - ./beat-orientation/ja/
#          - ./metadivision/index.md
#          - ./three-n-rhythm/index.md
          - ./distributed-groove-theory/ja/
          - ./offbeat-count-theory/ja/
#          - ./practical-offbeat-count/index.md
#          - ./polyrhythm/index.md
          - ./tatenori-and-psychology/index.md
#          - ./mechanism-behind-tatenori/index.md
#          - ./influence-of-japanese-language-on-cognition/index.md
