project:
  title: "リズムペディア.com"
  type: website
  output-dir: .site
  preview:
    port: 4141
    browser: false
  resources:
    - ads.txt

website:
  title: "リズムペディア.com"
  description: "グルーヴを科学するリズムペディア.com"
  site-url: "https://rhythmpedia.com/"
#  site-url: "https://ats4u.github.io/jpn-master-workinglog-markdown/"
#  announcement:
#    content: |
#       <div class="top-banner">
#       <img src="attachments/rhythmpedia-header3.png" style="width:100vw"/>
#      </div>
#    type: primary
#    position: above-navbar
#    dismissable: false
  navbar:
    right:
      - href: index.md
        text: "リズムペディアホーム"
    logo: attachments/rhythmpedia-header2.png
  sidebar:
    style: "docked"
    search: true
    contents:
      - text:  "リズムペディアホーム"
        href: index.md
      - section: "日本人のリズム感"
        contents: tatenori-theory/*.md
      - section: "裏拍基軸リズム理論"
        contents: offbeat-oriented-rhythm-theory/*.md
      - section: "メタディヴィジョン理論"
        contents: metadivision-theory/*.md
      - section: "3^nリズム理論"
        contents: three-n-rhythm-theory/*.md
      - section: "ポリリズム理論"
        contents: offbeat-oriented-polyrhythm-theory/*.md
      - text: "エッセイ"
        href: essays/*.md
    logo: /attachments/rhythmpedia-header5v2.png
format:
  html:
    theme:
      light : [ cosmo, theme.scss, theme-light.scss ]
      dark  : [ darkly, theme.scss, theme-dark.scss ]
    filters:
      - filters/include-files.lua
      - filters/obsidian-image-dimensions.lua
    css: styles.css
#    include-in-header:
#      - file: banner.html
    toc: true
    toc-location: right
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6838486775293179" crossorigin="anonymous"></script>

