
website:
  sidebar:
    contents:
#      - beat-orientation/ja/index.qmd
#      - metadivision/index.md
#      - three-n-rhythm/index.md
      - distributed-groove-theory/ja/index.qmd
      - offbeat-count-theory/index.qmd
#      - practical-offbeat-count/index.md
#      - polyrhythm/index.md
      - weak-beat-as-sun-strong-beat-as-earth/master-ja.qmd
      - tatenori-and-psychology/index.md
      - mechanism-behind-tatenori/index.md
#      - influence-of-japanese-language-on-cognition/index.md
