---
title: 武道としてのリズムの道
format: html
execute:
  enabled: true
  echo: false
  output: true
  eval: true
  cache: false
title-block: false
---
<style>
.quarto-title h1 {
  font-size: 2.5em;
  margin:0px;
  padding:0px;
}
ul {
    margin: 0;
    padding: 0 0 0 0.0em;
}
ul ul {
    margin: 0;
    padding: 0 0 0 1.5em;
}

h2.hiddenh2 {
  display:none;
}
ruby {
  ruby-position: over; /* ensure consistent structure */
}

ruby.inline-ruby rt {
  display: inline;              /* make <rt> flow inline */
  font-size: inherit;           /* match text size */
  font-style: normal;
  margin-left: 0.2em;
}
ruby.inline-ruby rt::before {
  content: "《";
}
ruby.inline-ruby rt::after {
  content: "》";
}
</style>

## {{<var RUBY-RDO>}}とは {.hiddenh2}

<!-- J5S+/sJLoORbqNfYzL8kdQ== -->

**律武道《りつぶどう》**は『スイング』『フロー』『真のジャズのリズム』などと呼ばれる**グルーヴ**を演奏する技術と精神を極める為の武道です。律武道は、これまで曖昧に感覚として捉える以外なかった神秘的なリズムの世界＝**グルーヴ**を、音韻学的に分析し理論化した**{{<var RUBY-HGT>}}**にその基礎を置いた上で、更に日本人の精神、礼儀作法、謙譲と配慮の文化を統合し武道として体系化したものです。

ここでいう**武**とは、**衝突を避けるのではなく、むしろ積極に誘発し、怒り、苛立ち、嫉み、妬み、嫌悪などの否定的な感情をまず解き放ち、人々の精神を自由に解き放った上で、喜び・愛情・友情・絆・笑いへと昇華させるテクノロジーとしての『オフビートカウント』** を意味します。この**{{<var RUBY-RDO>}}**の『武』は、全ての人を否定的感情から解放し、全ての人が協力して幸せになることができる調和のあふれる健全な社会を作り出す力** ... **止戈為武（しかいぶ）** を本当の意味で実現することを究極の目的とする新次元の武を表します。

**{{<var RUBY-RDO>}}**は、**ジャズの即興演奏**という**{{<var RUBY-IRSK>}}**の全てを震わせる必要のある技能を極めることを通じて、日本人としてふさわしい礼儀作法と武道の精神を学び、多文化多様性を常に尊重できる敬意と、柔軟な人間力を身につけ、真の英語のリズム**グルーヴ**によって国際社会で積極的に発言出来る高いコミュニケーション力を身につけ、日本文化の素晴らしさを伝えることが出来る人間力を鍛えることをその究極の目的とします。

**{{<var RUBY-RDO>}}**の究極の目的、それは、社会に役立つ人材を育成し社会に貢献することのみに留まらず、人種の差、文化の差、言語の差、そしてリズムの差を乗り越える真のコミュニケーション力を身につける武道を全世界にあまねく行き渡らせることによって、世界平和を実現することです。

**{{<var RUBY-RDO>}}**は３つの字によって成り立っています。

**律**は即ち、法則、秩序、律動です。<ruby>律動<rt>ジャズ</rt></ruby>、<ruby>音楽<rt>インプロヴィゼーション</rt></ruby>、<ruby>語学<rt>スピーキング</rt></ruby>、<ruby>舞踊<rt>ダンス</rt></ruby>のそれぞれに一貫するリズムの原理を表しています。

**武**は即ち、リズムという名の音楽的<ruby>暴力<rt>ヴァイオレンス</rt></ruby>を <ruby>諫<rt>いさ</rt></ruby>め、**{{<var RUBY-SOUL>}}**を学び、究極の<ruby>霊性<rt>スピリット</rt></ruby>に到達するグルーヴを極める道程としての武を表しています。

**道**は即ち、終わりない鍛錬を通じ極めるべき道程を表しています。

これが**{{<var RUBY-RDO>}}**です。

**{{<var RUBY-RDO>}}**は、**{{<var RUBY-HGT>}}**を基盤に置いた上で４つの体系から成り立っています。

**韻律武道**  
音韻学のストレス拍リズムを音楽リズムに応用し英語のリスニング・スピーキングの道を極めます。

**旋律武道**  
音楽理論のアベイラブルスケールノート理論を超グルーヴ理論を踏まえた上で学び習得します。

**和律武道**  
音楽理論の和声理論を超グルーヴ理論を踏まえた上で学んで習得します。

**動律武道**  
音韻学のストレス拍リズムをダンスに応用しダンスグルーヴの道を極めます。

**{{<var RUBY-RDO>}}**の精神は次の様なものがあります。

**律動武 ─── リズムは暴力**  
**{{<var RUBY-RDO>}}**では、音楽は人間のぶつかりあいであることをはっきりと意識し、リズムが暴力の一種であることをはっきり意識します。暴力であるがゆえに、相手の人格を尊重しいたずらに傷つけることがないように配慮する礼儀作法が重要になります。

**礼儀作法**  
リズムの暴力性をはっきり意識した上で礼儀作法を重視し、遠慮なく自他ともに実力を全て出し切る為の精神的な基盤作りを重視します。他者の精神と文化を尊重し、相手が真剣に格闘に向き合うことが出来るように自分自身も真剣に格闘に向き合うことを重視します。

**霊魂心**  
日本の伝統的な概念**<ruby>霊魂心<rt>れいこんしん</rt></ruby>**に則って、常に相手の崇高な霊性に語りかけることを重視し、いたずらに相手の心をなじるようなことがないよう常に心がけます。

**{{<var RUBY-IRSK>}}**  
人の魂が持つ四魂の全て愛、親、智、勇を磨き、<ruby>直霊<rt>なおひ</rt></ruby>に立つ修練としての武道を極めることを重視します。

**音楽の{{<var RUBY-KTTM>}}**  
言葉は人を活かしもすれば殺しもする ─── 同じ用に音楽における旋律・律動も同じように<ruby>霊<rt>たましい</rt></ruby>であり、それを受け取る人を活かしもすれば殺しもします。
**怒りを笑いへと解き放つ**  
リズムは即ち、緊張・緊張・摩擦・衝突・怒り・悲しみなどの否定的感情でもあります。これらをむしろ解放することで、苛立ち怒り嘆きなどの<ruby>破壊的感情<rt>ネガティヴィティ</rt></ruby> を喜びや愛などの<ruby>創造的感情<rt>ポジティヴィティ</rt></ruby> へ変換する力であるグルーヴを研究します。

**真のコミュニケーション力**  
律動理論が真の国際コミュニケーション力の源であることを意識し、それを実践するとともに、全拳士が律動理論こそが真の国際コミュニケーション力となりうることを、一人でも多くの人々に伝える責務を負います。

**音楽力の養成**  
人を動かす音楽の原動力こそがグルーヴであり、グルーヴ力を身につけることは即ち、人を感動させる力となります。人を動かす力をつけることが**{{<var RUBY-RDO>}}**の本質的目標です。

**国際力**  
現代ビジネスの世界では英語から直接情報を理解する能力が必須になりつつあります。ただ単に英語の文章を理解するだけでなく、基本論調や公演のビデオを直接見てリアルタイムで理解する能力が求められています。英語は表音文字の言語です。英語の思考法とコミュニケーション力を身につける為には音声を直接理解する必要があります。日本人が英語を音から理解することを阻害しているもの、それが『縦乗り＝裏拍が聴き取れない』＝末子音をもたない日本語を母国語とする人の宿命です。

**{{<var RUBY-RDO>}}**は超グルーヴ・オフビートカウント理論を応用することで、裏拍が聴き取れないという弱点を克服します。これが英語の末子音が聴き取れない問題をピンポイントで解決。突如として英語が明瞭に聴き取れる様になります。

**論理力**  
ITを生業とするものであれば誰でも英語に課題を持っていることでしょう。英語で情報収集することはもはや必須です。しかし英語は音声に基づいた言語です。英語の音声を聴いてみると、実は韻を踏んでキャッチーに聞こえる様になっている技術用語や、実は音声を聴くと即座に気付くであろう駄洒落の語呂合わせになっている技術用語がたくさんあります。 ─── AIで英語を翻訳しているだけでは、彼らが考えていることを本当に理解したとは言えないのです。

何故日本人は英語が聴き取れないのか。それはRが苦手だからでもTHで舌を噛むことが出来ないことでもありません。「裏拍が聴き取れない＝末子音が聴き取れない」ことです。末子音が聴き取れれば、全て聴き取れるようになります。何故海外の人はすぐに英語が話せるのか。それは全世界の言語は必ず末子音を持っているからです。日本語だけが末子音を持っていないのです。

**科学力**  
学術を生業とするものであれば誰でも英語に課題を持っていることでしょう。 全ての論文は英語で書かれています。しかし如何にそれが文法的に正しく理解可能なものであっても、それが音声としてどの様に人に伝わっているのかを感じ取ることが出来なければ、それは本当の意味で相手に伝わったとは言えません。相手が特定のリズムと音声効果を 如何に説得力を持って相手に響いているのか ─── これを考えるものが**{{<var RUBY-RDO>}}**の超グルーヴ理論です。逆も又然りといえます。英語を話す科学者はしばしば、それを語呂合わせや駄洒落などに載せて説明しているものです。この駄洒落の意味がわからなければ、それを理解することは出来ません。 これはAIを使って日本語に翻訳しても状況は何も改善しない根本的な問題といえます。

**オフビートで思考する語学**  
プログラミングの様々な概念が、実は英語の文法と密接な関係を持っていることを御存知でしょうか。メタクラス・クラス・オブジェクト・これらは英語の**冠詞**と深い関連を持っています。しかし日本語は冠詞を持ちません。では日本語を話す人は冠詞を教科書を読んで理解すれば、それを理解することが出来るでしょうか。 ─── 出来ません。何故ならは**冠詞はしばしば裏拍で発音される**からです。 いくらそこに冠詞があることを知っていても、そこに冠詞があることをどんなに意識しても、裏拍が聴き取れない日本人は、冠詞を聴き取ることができないのです。

そんな裏拍が聴き取れない日本人の弱点をピンポイントで修正するもの ─── それが超グルーヴ・オフビートカウント理論です。オフビートカウント修行は長い道のりです。これを迷うことなく誰もがまっすぐと本質に向かってあることが出来るように体系化した武道が**{{<var RUBY-RDO>}}**です。

**道**  
正しい理論に基づいて体系化された型を繰り返し練習することによって、グルーヴを体得し、その言葉にグルーヴを携える、その音楽にグルーヴを帯びるようになることができます。

**神道**  
神道で古くから語り継がれる日本人の霊魂心・一霊四魂・言靈・志といった概念に則ってグルーヴを研究し体得します。

**世界平和**  
**{{<var RUBY-RDO>}}**は、神道思想のもと、宗教人種文化言語の別け隔てのない自由な世界の創出を目指します。

**{{<var RUBY-RDO>}}** は次の事柄を重視して実践します。

**自己鍛錬**  
リズム理論を学ぶことで粘り強さと柔軟な理解力を身につける。

**人格形成**  
リズム練習は心身を鍛え、怒りを笑いへ変える人間力を磨く。

**実戦性と社会性**  
ジャムセッションで他者との精神的なぶつかりあいを体験することで、大きな生活の中ではっきりと意見を述べながら協調出来る高度な社会性を育みます。

**尊敬、感謝、忍耐**  
**{{<var RUBY-RDO>}}**は武道として、共に学ぶ拳士への敬意と感謝を大切にします。

**{{<var RUBY-RDO>}}** は、理に沿って道を極めることを重視します。

律武道が基盤とする理論は <span style="font-weight:1000;font-size:150%">{{<var RUBY-HGT2>}}</span>です。

---

```{python}
#| output: asis
from pathlib import Path
from rhythmpress import rhythmpress
out = rhythmpress.create_global_navigation( '_rhythmpress.conf', 'ja', strict=False )
print(out)
```

-------

{{<var RUBY-RDO>}} は、ミュージシャン、語学学習者、教育者をはじめ、TOEIC900点を取ったけど全く英語が話せない事に悩む貴方や、英語の壁に苦しむプログラマー、英語論文の執筆に悩む研究者など、縦乗りと横乗りの架け橋になる理論ポータルサイトです。

<!-- vim: set wrap ts=2 sw=2 isk+=- breakat= ve=all : -->
