website:
  sidebar:
    contents:
      - section: "<ruby><rb>多層弱拍基軸律動</rb><rt>グルーヴィダンスミュージック</rt></ruby>理論"
        contents:
          - beat-orientation/benefits-of-multi-layered-weak-beat-oriented-rhythm-theory/ja/index.qmd
          - beat-orientation/headians-and-bottomians-of-beat-orientation/ja/index.qmd
          - beat-orientation/phonological-analysis-of-rhythm-types-in-languages/ja/index.qmd
          - beat-orientation/letter-to-native-mora-timed-speakers/ja/index.qmd
          - beat-orientation/the-crossing-point-of-language-and-music/ja/index.qmd
          - beat-orientation/multi-layered-weak-beat-precedence/ja/index.qmd
          - beat-orientation/multi-layered-weak-beat-oriented-rhythm-theory-summary/ja/index.qmd
          - beat-orientation/weakbeat-geocentrism-vs-heliocentrism/ja/index.qmd
          - beat-orientation/mechanism-of-tatenori/ja/index.qmd
