name: Build & Deploy Rhythmpedia (rhythmpress)

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Point rhythmpress to the site root
      RHYTHMPRESS_ROOT: ${{ github.workspace }}

    steps:
      - name: Checkout site repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # full history for per-file git dates

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install system deps (Quarto + yq + LilyPond + pandoc)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget lilypond pandoc
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.31"
      - name: Install yq
        run: |
          YQ_VERSION=v4.47.1
          sudo wget -q https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version

      # -------- rhythmpress: clone + install --------
      - name: Clone rhythmpress
        uses: actions/checkout@v4
        with:
          repository: ats4u/rhythmpress.git   # <-- change me
          ref: master                                        # <-- change if needed
          path: vendor/rhythmpress
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install rhythmpress (pip install .)
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter pyyaml
          pip install ./vendor/rhythmpress

      # Optional: show versions for debugging
      - name: Show tool versions
        run: |
          python --version
          pip --version
          rhythmpress --help | head -n 20
          quarto --version

      # -------- Build & Render --------
      - name: Build with rhythmpress
        run: |
          # If you require its env shim, uncomment next line:
          eval "$(rhythmpress env)"
          rhythmpress build

      - name: Render Quarto project
        env:
          QUARTO_PROJECT_DIR: ${{ github.workspace }}
        run: quarto render

      # -------- Deploy --------
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.site
          publish_branch: gh-pages

