on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.7.31"
#          version: "1.4.550"
      - name: Install yq
        run: |
            YQ_VERSION=v4.47.1
            wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/local/bin/yq
            chmod +x /usr/local/bin/yq
            yq --version
      - name: Install Python (if needed)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Jupyter and YAML support
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter pyyaml
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

#      - name: Install R (if needed for R-based docs)
#        uses: r-lib/actions/setup-r@v2

      - name: Build and Run Sidebar Renderer
        run: |
          ./build
      - name: Render Quarto project
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.site
          publish_branch: gh-pages

